---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r setup, warning=F, message=F}
# DO NOT CHANGE THESE OPTIONS

knitr::opts_chunk$set(echo = TRUE)
options(knitr.duplicate.label = "allow")

rm(list = ls())

# Libraries
library(tidyverse)
library(haven)
library(readr)
library(modelsummary)
library(gt)
library(kableExtra)
library(webshot2)
library(pdftools)

# Theme for Tables, based on the apa theme created for GT
# source: https://gist.github.com/pdparker/1b61b6d36d09cb295bf286a931990159
apa_style <- function(data) {
  data %>%
    opt_table_lines(extent = "none") %>%
    tab_options(
      table.align = "left",
      heading.border.bottom.width = 2,
      heading.border.bottom.color = "black",
      heading.border.bottom.style = "solid",
      table.border.top.color = "white",
      table_body.hlines.color = "white",
      table_body.border.top.color = "black",
      table_body.border.top.style = "solid",
      table_body.border.top.width = 1,
      heading.title.font.size = 16,
      table.font.size = 12,
      heading.subtitle.font.size = 14,
      heading.align = "left",
      table_body.border.bottom.color = "black",
      table_body.border.bottom.width = 2,
      table_body.border.bottom.style = "solid",
      column_labels.border.bottom.color = "black",
      column_labels.border.bottom.style = "solid",
      column_labels.border.bottom.width = 1,
      data_row.padding = px(5)
    ) %>%
      opt_table_font(font = "georgia")
}
```

```{r table-functions, warning=F, message=F}
# Paste these functions into your R document (DO NOT ALTER)

# Code for creating summary table on all numeric variables in the dataset
Allnumeric2 <- function(df){
datasummary(All(df, numeric=TRUE) ~ 
            ((Obs. = N) + (Avg. = Mean) + (Std.Dev. = SD) + (Min. = Min) + (Max. = Max)),
            data = df,
            output = 'gt') %>% 
  apa_style() %>% 
  cols_align(align = "center", columns = 2:(ncol(df) - 1))  %>% 
  tab_header(title = "Table Number", subtitle = md("*Change to a Descriptive Title for the Table*") ) %>% 
  tab_footnote(footnote = md( "*Note*: Possible footnote for table.") ) %>%
  tab_footnote(footnote = "Second possible footnote for table.")  %>%
  tab_options(table.width = pct(50))
}

# Code for creating  summary table for all categorical variables in the dataset
Allcat2 <- function(df){
datasummary(All(df, numeric=FALSE, factor=TRUE) ~ 
            ((Obs. = N) + Percent() ),
            data = df,
            output = 'gt') %>% 
  apa_style() %>% 
  cols_align(align = "center", columns = 3:4)  %>% 
  tab_header(title = "Table Number", subtitle = md("*Change to a Descriptive Title for the Table*") ) %>%   
  tab_footnote(footnote = md( "*Note*: Possible footnote for table.") ) %>%
  tab_footnote(footnote = "Second possible footnote for table.")  %>%
    cols_width(
    columns = c(1) ~ px(100),
    columns = c(2:4) ~ px(75)  ) 
}

# Code for creating  summary table for all numeric variables by a group variable
Crossnum <- function(df, var1){
datasummary(All(df, numeric=TRUE) ~ 
            var1 * ((Avg. = Mean) + (Std.Dev. = SD)),
            data = df,
            output = 'gt') %>% 
  apa_style() %>% 
  cols_align(align = "center", columns = 2:(ncol(df) - 2))  %>% 
  tab_header(title = "Table Number", subtitle = md("*Change to a Descriptive Title for the Table*") ) %>% 
  tab_footnote(footnote = md( "*Note*: Possible footnote for table.") ) %>%
  tab_footnote(footnote = "Second possible footnote for table.")  %>%
  tab_options(table.width = pct(50))
}

# Code for creating  summary table for all categorical variables by a group variable
Crosscat <- function(df, var1){
datasummary(All(df[!myvars], numeric=FALSE, factor=TRUE, character = FALSE) ~ 
            var1 * ((Obs. = N) + Percent() ) ,
            data = df,
            output = 'gt') %>% 
  apa_style() %>% 
  cols_align(align = "center", columns = 3:(ncol(df) - 2))  %>% 
  tab_header(title = "Table Number", subtitle = md("*Change to a Descriptive Title for the Table*") ) %>% 
  tab_footnote(footnote = md( "*Note*: Possible footnote for table.") ) %>%
  tab_footnote(footnote = "Second possible footnote for table.")  %>%
  tab_options(table.width = pct(50))
}

# Code for creating combined summary table (numeric and categorical) by a group variable
Combinedtable <- function(df, var1){
var1 <- ensym(var1)  
fac <- as.formula(paste("~", as.character(var1)))

datasummary_balance(fac,
                    data = df, output = 'gt',
                    dinm = F) %>% 
  apa_style() %>%
  cols_align(align = "center", columns = 3:(ncol(df) - 1))  %>% 
  tab_header(title = "Table Number", subtitle = md("*Change to a Descriptive Title for the Table*") ) %>%   
  tab_footnote(footnote = md( "*Note*: Possible footnote for table.") ) %>%
  tab_footnote(footnote = "Second possible footnote for table.") %>%
  tab_options(table.width = pct(60)) #  %>%  gtsave("table_example.pdf")
}
```

```{r cleaning-data}
# This converts the the dataset into a dataframe
# Necessary to run some of the functions for datasummary 

# Make dataset into a dataframe
# Change df1 to the name of your original dataset
df2 <- data.frame(rbind(df1))

# Convert all Character Variables to Factors
# Change df2 if necessary (will be whatever you name the data.frame)
df2[sapply(df2, is.character)] <- lapply(df2[sapply(df2, is.character)],  as.factor)

# Replace 0 or missing value with NA
df2 <- df2 %>% mutate_if(is.numeric, ~replace(., . == 0, NA))

# Replace possible infinite values with NA
df2[sapply(df2, is.infinite)] <- NA

# Also need to set this initial option, where you list the dataset of interest 
#and the variable that you want to utilize as your "grouping" variable
myvars <- names(df2) %in% c("var1") 
```

```{r table-outputs}
Allnumeric2(df2) %>% 
  gtsave("Table1.pdf")

Allcat2(df2) %>% 
  gtsave("Table2.pdf")

Crossnum(df2, df2$Treatment) %>% 
  gtsave("Table3.pdf")

Crosscat(df2, df2$Treatment) %>% 
  gtsave("Table4.pdf")

Combinedtable(df2, Treatment) %>% 
  gtsave("Table5.pdf")
```

```{r table-pdf}
pdf_combine(c("Table1.pdf", "Table2.pdf", "Table3.pdf", "Table4.pdf", "Table5.pdf"), 
            output = "Tables.pdf")
```