---
title: "Descriptive Statistics Table"
date: "`r Sys.Date()`"

output: 
  html_document:
      toc: true
      theme: lumen
      highlight: textmate
      
# Author Comment: Updated file after working more with both the HTML and Latex files
# Made some changes to the theme from the previous file    
---

```{r setup, include=FALSE}

# DO NOT CHANGE THESE OPTIONS
knitr::opts_chunk$set(echo = TRUE)
options(knitr.duplicate.label = "allow")

rm(list = ls())

# Libraries
library(tidyverse)
library(haven)
library(readr)
library(modelsummary)
library(gt)

# Theme for Tables
# Based on the apa theme created for GT
# source: https://gist.github.com/pdparker/1b61b6d36d09cb295bf286a931990159
apa_style <- function(data) {
  data %>%
    opt_table_lines(extent = "none") %>%
    tab_options(
      heading.border.bottom.width = 2,
      heading.border.bottom.color = "black",
      heading.border.bottom.style = "solid",
      table.border.top.color = "white",
      table_body.hlines.color = "white",
      table_body.border.top.color = "black",
      table_body.border.top.style = "solid",
      table_body.border.top.width = 1,
      heading.title.font.size = 12,
      table.font.size = 12,
      heading.subtitle.font.size = 12,
      heading.align = "left",
      table_body.border.bottom.color = "black",
      table_body.border.bottom.width = 2,
      table_body.border.bottom.style = "solid",
      column_labels.border.bottom.color = "black",
      column_labels.border.bottom.style = "solid",
      column_labels.border.bottom.width = 1
    ) %>%
      opt_table_font(font = "times")
}
```

```{r include=FALSE}
# Switch the dataset by completing the following steps:
  ## Click on the Import Dataset dropdown menu from the Environment pane (top right corner).
  ## Select the file extension from the options listed.
  ## Either enter the file name or select "browse" in the top line of the prompt.
  ## Once the file has been selected, name the dataset under the import options box and click "import".

#Distict_Turnout <- read_dta("~/Dropbox (UNC Charlotte)/UI-Summary Reporting Templates/Data/Example2.dta")
District_Turnout <- read_dta("Example2.dta")
glimpse(District_Turnout)
```


```{r, include=FALSE, eval=FALSE}
# This is the template to follow
# There is no need to change anything in this code
datasummary(vars ~ 
            ( (Obs. = NUnique) + (Avg. = Mean) + (Std.Dev. = SD) + (Min. = Min) + (Max. = Max) ),
            data = data.frame.name,
            output = 'gt') %>% 
  apa_style() %>% 
  cols_align(align = "center", columns = 2:6)  %>% 
  tab_header(title = "Table Number", subtitle = md("*Descriptive table title*") ) %>% 
  tab_footnote(footnote = md( "*Note*: Possible footnote for table.") ) %>%
  tab_footnote(footnote = "Second possible footnote for table.")

# What researchers need to change in the code above (copy and pasted below):
  ## vars: this line allows researchers to list the variables of interest; it is important to understand this function as written only focuses on continuous variables. Do not include categorical variables in this particular function as the statistics will not be relevant.
  ## data.frame.name: this is the dataset you imported into the R environment. 
```

```{r descriptive, echo=FALSE}
datasummary(turnout + electorateunion + turnoutch  ~ 
            ( (Obs. = NUnique) + (Avg. = Mean) + (Std.Dev. = SD) + (Min. = Min) + (Max. = Max) ),
            data = District_Turnout,
            output = 'gt') %>% 
  apa_style() %>% 
  cols_align(align = "center", columns = 2:6)  %>% 
  tab_header(title = "Table Number", subtitle = md("*Descriptive table title*") ) %>% 
  tab_footnote(footnote = md( "*Note*: Possible footnote for table.") ) %>%
  tab_footnote(footnote = "Second possible footnote for table.")
```

